"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{

[flavor]
dark  = ""
light = ""

# : }}}


# : App {{{

[app]
overall = {}

# : }}}


# : Manager {{{

[mgr]
cwd = { fg = "#faa1ff" }

# Find
find_keyword  = { fg = "#faa1ff", bold = true, italic = true, underline = true }
find_position = { fg = "magenta", bg = "reset", bold = true, italic = true }

# Symlink
symlink_target = { italic = true }

# Marker
marker_copied   = { fg = "lightgreen",  bg = "lightgreen" }
marker_cut      = { fg = "lightred",    bg = "lightred" }
marker_marked   = { fg = "lightcyan",   bg = "lightcyan" }
marker_selected = { fg = "lightyellow", bg = "lightyellow" }

# Count
count_copied   = { fg = "white", bg = "#26a65b" }
count_cut      = { fg = "white", bg = "#f53c3c" }
count_selected = { fg = "black", bg = "#faa1ff" }

# Border
border_symbol = "│"
border_style  = { fg = "#faa1ff" }

# Highlighting
syntect_theme = ""

# : }}}


# : Tabs {{{

[tabs]
active   = { bg = "#faa1ff", bold = true }
inactive = { fg = "#faa1ff", bg = "black" }

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}


# : Mode {{{

[mode]
normal_main = { bg = "#faa1ff", bold = true }
normal_alt  = { fg = "#faa1ff", bg = "black" }

# Select mode
select_main = { bg = "#faa1ff", bold = true }
select_alt  = { fg = "#faa1ff", bg = "black" }

# Unset mode
unset_main = { bg = "#faa1ff", bold = true }
unset_alt  = { fg = "#faa1ff", bg = "black" }

# : }}}


# : Indicator of hovered file {{{

[indicator]
parent  = { reversed = true }
current = { reversed = true }
preview = { underline = true }
padding = { open = "", close = "" }

# : }}}


# : Status bar {{{

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep   = { fg = "#faa1ff" }
perm_type  = { fg = "#faa1ff" }
perm_read  = { fg = "#faa1ff" }
perm_write = { fg = "#faa1ff" }
perm_exec  = { fg = "#faa1ff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#26a65b", bg = "black" }
progress_error  = { fg = "#ffbe61", bg = "#f53c3c" }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "#faa1ff" }
cand            = { fg = "#faa1ff" }
rest            = { fg = "#faa1ff" }
desc            = { fg = "#faa1ff" }
separator       = "  "
separator_style = { fg = "#faa1ff" }

# : }}}


# : Confirmation {{{

[confirm]
border     = { fg = "#faa1ff" }
title      = { fg = "#faa1ff" }
body       = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ "  Y - SI  ", "  N - NON " ]

# : }}}


# : Spotter {{{

[spot]
border = { fg = "#faa1ff" }
title  = { fg = "#faa1ff" }

# Table
tbl_col  = { fg = "#faa1ff" }
tbl_cell = { fg = "#faa1ff", reversed = true }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#faa1ff" }
title_warn  = { fg = "#ffbe61" }
title_error = { fg = "#f53c3c" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : Picker {{{

[pick]
border   = { fg = "#faa1ff" }
active   = { fg = "#faa1ff", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#faa1ff" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border   = { fg = "#faa1ff" }
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Task manager {{{

[tasks]
border  = { fg = "#faa1ff" }
title   = {}
hovered = { fg = "#faa1ff", bold = true }

# : }}}


# : Help menu {{{

[help]
on      = { fg = "#faa1ff" }
run     = { fg = "#faa1ff" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "black", bg = "#FFFFFF" }

# : }}}


# : File-specific styles {{{

[filetype]
rules = [
	# Image
	{ mime = "image/*", fg = "#faa1ff" },
	# Media
	{ mime = "{audio,video}/*", fg = "#faa1ff" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#faa1ff" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#faa1ff" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#faa1ff" },
	# Special file
	{ url = "*", is = "orphan", bg = "#faa1ff" },
	{ url = "*", is = "exec"  , fg = "#faa1ff" },
	# Dummy file
	{ url = "*", is = "dummy", bg = "#faa1ff" },
	{ url = "*/", is = "dummy", bg = "#faa1ff" },
	# Fallback
	{ url = "*/", fg = "#faa1ff" }
]

# : }}}


# : Icons {{{

[icon]
globs = []
dirs  = [
	{ name = ".config", text = "", fg = "#faa1ff" },
	{ name = ".dotfiles", text = "", fg = "#faa1ff" },
	{ name = ".git", text = "", fg = "#faa1ff" },
	{ name = ".github", text = "", fg = "#faa1ff" },
	{ name = ".npm", text = "", fg = "#faa1ff" },
	{ name = "Aplicacións", text = "", fg = "#faa1ff" },
	{ name = "Escritorio", text = "", fg = "#faa1ff" },
	{ name = "Desarrollo", text = "", fg = "#faa1ff" },
	{ name = "Documentos", text = "", fg = "#faa1ff" },
	{ name = "Descargas", text = "", fg = "#faa1ff" },
	{ name = "Libería", text = "", fg = "#faa1ff" },
	{ name = "Películas", text = "", fg = "#faa1ff" },
	{ name = "Música", text = "", fg = "#faa1ff" },
	{ name = "Imaxes", text = "", fg = "#faa1ff" },
	{ name = "Público", text = "", fg = "#faa1ff" },
	{ name = "Vídeos", text = "", fg = "#faa1ff" },
	{ name = "Xogos", text = "", fg = "#faa1ff" },
	{ name = "Modelos", text = "", fg = "#faa1ff" },
]
files = []
exts = []
conds = [
	# Special files
	{ if = "orphan", text = "", fg = "#faa1ff" },
	{ if = "link", text = "", fg = "#faa1ff" },
	{ if = "block", text = "", fg = "#faa1ff" },
	{ if = "char", text = "", fg = "#faa1ff" },
	{ if = "fifo", text = "", fg = "#faa1ff" },
	{ if = "sock", text = "", fg = "#faa1ff" },
	{ if = "sticky", text = "", fg = "#faa1ff" },
	{ if = "dummy", text = "", fg = "#faa1ff" },

	# Fallback
	{ if = "dir", text = "", fg = "#faa1ff" },
	{ if = "exec", text = "", fg = "#faa1ff" },
	{ if = "!dir", text = "", fg = "#faa1ff" },
]

# : }}}
